/******************************************************************************************************************
 * NurseService.java
 *
 *          Provides the CRUD operations and certain find queries for getting the nurse data.
 *
 * @author Matthew Kiyono
 * @since 12/6/2025
 * @version 1.0
 ******************************************************************************************************************/
package com.appointmentProject.backend.service;

import com.appointmentProject.backend.exception.RecordNotFoundException;
import com.appointmentProject.backend.model.Nurse;
import com.appointmentProject.backend.repository.NurseRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class NurseService {

    @Autowired
    private NurseRepository nurseRepo;

    // CREATE
    public Nurse addNurse(Nurse nurse) {
        // ID will be auto-generated by MySQL
        return nurseRepo.save(nurse);
    }

    // READ ALL
    public List<Nurse> getAllNurses() {
        return nurseRepo.findAll();
    }

    // READ ONE
    public Nurse getById(int id) {
        return nurseRepo.findById(id)
                .orElseThrow(() ->
                        new RecordNotFoundException("Nurse with id " + id + " not found.")
                );
    }

    // UPDATE
    public Nurse updateNurse(int id, Nurse updated) {
        Nurse existing = getById(id); // throws if not found

        existing.setFirstName(updated.getFirstName());
        existing.setLastName(updated.getLastName());
        existing.setPhone(updated.getPhone());
        existing.setEmail(updated.getEmail());
        existing.setAddress(updated.getAddress());

        return nurseRepo.save(existing);
    }

    // DELETE
    public void deleteNurse(int id) {
        if (!nurseRepo.existsById(id)) {
            throw new RecordNotFoundException("Cannot delete. Nurse with id " + id + " not found.");
        }
        nurseRepo.deleteById(id);
    }
}

