/*************************************************************************
 *  ProviderCreateController.java
 *
 *      This controller is responsible for providing admin users the "form"
 *      to creating a new Provider. Each provider is given a unique id upon
 *      creation (by the autogenerated database feature). Their first and
 *      last names are composite keys that are unique within the Provider
 *      table. Emails are also unique within the Provider table (meaning
 *      the first/last name combo and email can exist outside of this
 *      table). None of the fields can be null.
 *
 * @author Matthew Kiyono
 * @version 1.0
 * @since 12/3/2025
 **************************************************************************/
package com.appointmentProject.desktop.controller;

import com.appointmentProject.desktop.SceneNavigator;
import com.google.gson.JsonObject;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;

import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;

public class ProviderCreateController {

    @FXML private TextField firstNameField;
    @FXML private TextField lastNameField;
    @FXML private TextField phoneField;
    @FXML private TextField emailField;
    @FXML private TextField specialtyField;
    @FXML private TextField addressField;

    @FXML private Label messageLabel;

    @FXML
    public void handleCreateProvider() {

        try {
            // Validate
            if (firstNameField.getText().isEmpty() ||
                    lastNameField.getText().isEmpty() ||
                    phoneField.getText().isEmpty() ||
                    emailField.getText().isEmpty() ||
                    specialtyField.getText().isEmpty() ||
                    addressField.getText().isEmpty()) {

                messageLabel.setText("All fields must be filled.");
                return;
            }

            // Build JSON body
            JsonObject body = new JsonObject();
            body.addProperty("firstName", firstNameField.getText().trim());
            body.addProperty("lastName", lastNameField.getText().trim());
            body.addProperty("phone", phoneField.getText().trim());
            body.addProperty("email", emailField.getText().trim());
            body.addProperty("specialty", specialtyField.getText().trim());
            body.addProperty("address", addressField.getText().trim());

            URL url = new URL("http://localhost:8080/provider/add");
            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("POST");
            con.setRequestProperty("Content-Type", "application/json");
            con.setDoOutput(true);

            OutputStream os = con.getOutputStream();
            os.write(body.toString().getBytes());
            os.flush();
            os.close();

            int status = con.getResponseCode();

            if (status == 200) {
                messageLabel.setStyle("-fx-text-fill: green;");
                messageLabel.setText("Provider created successfully!");
            } else {
                messageLabel.setText("Server error: Could not create provider.");
            }

        } catch (Exception e) {
            e.printStackTrace();
            messageLabel.setText("Error connecting to server.");
        }
    }

    @FXML
    public void handleBack() {
        SceneNavigator.switchTo("/fxml/provider_list.fxml");
    }
}
